### ISSUE TITLE
Disable hyperthreading

### ISSUE THREAD

**Issue by nstornetta** [aws-samples/aws-parallelcluster-price-performance#1]
https://github.com/aws-samples/aws-parallelcluster-price-performance/blob/e428cf59c191fbcba7284b8838f4fda5a78aabdb/conf.ini#L39

In versions >= 2.5.0 of ParallelCluster, the post-install script being used to disable hyperthreading can be changed to the `disable_hyperthreading` parameter. We can leave in the post-install script for customers who are have older versions, but it would be a good idea to include a line for the parameter as well.

**Comment by ubik76** [comment]
I have update the conf.ini file with your comments
